server:
  port: 8081
spring:
  application:
    name: egar-test
  datasource:
    url: jdbc:postgresql://localhost:5432/egar-test
    username: someuser
    password: somepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always